theme: jekyll-theme-midnight
description: >- # this means to ignore newlines until "baseurl:"
Website for p1-Intellijs College Application Service
email: "kylem31415@gmail.com"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

